src/objects/Guidebook_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is batch size Settings for each batch</description>
    <fields>
        <fullName>Api_Key__c</fullName>
        <description>Api Key for Guidebook</description>
        <inlineHelpText>Api Key for Guidebook</inlineHelpText>
        <label>Api Key</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Organization_ID__c</fullName>
        <label>Organization ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>GuideBook Setting</label>
</CustomObject>

src/objects/LTE__Site__c.object
<CustomObject>
    <fields>
        <fullName>Guide__c</fullName>
        <externalId>true</externalId>
        <label>Guide ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/classes/Test_GuidebookController_MemberShip.cls
/*
* @author Hirdesh 
* @Date   01 JAN 2020
* @purpose This class will be used to cover TestCoverage of GuidebookRestApiController_MemberShip   
*/

@isTest
Private class Test_GuidebookController_MemberShip {
    
    @testSetup static void setup() {
        LTE__Site__c Comsite = new LTE__Site__c();
        Comsite.Name = 'TestSite';
        Comsite.LTE__Site_URL__c = 'https://google.com';
        Comsite.Guide__c = 10068 ;
        insert Comsite;
        
        LTE__Site__c Comsite1 = new LTE__Site__c();
        Comsite1.Name = 'TestSite1';
        Comsite1.LTE__Site_URL__c = 'http://google.com';
        Comsite1.Guide__c = 10069 ;
        insert Comsite1;
        
        Guidebook_Setting__c guide = new Guidebook_Setting__c();
        guide.Name = UserInfo.getUserName();
        guide.Api_Key__c = 'JWT '+'Test';
        guide.Organization_ID__c = 123456798;
        insert guide;
    }
    @isTest
    static void guidebookRestApiControllerPutTestMethod(){
        
        LTE__Site__c Comsite = [Select Id , Name , LTE__Site_URL__c , Guide__c from LTE__Site__c Where Name = 'TestSite' Limit 1];
        
        LTE__Site__c Comsite1 = [Select Id , Name , LTE__Site_URL__c , Guide__c from LTE__Site__c Where Name = 'TestSite1' Limit 1];
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        GuidebookRestApiController_MemberShip.getSite();
        GuidebookRestApiController_MemberShip.createGuide_Membership(Comsite.Id , 'Testing Guide' , 'Test Description');
        GuidebookRestApiController_MemberShip.createGuide_Membership(Comsite1.Id , 'Testing Guide' , 'Test Description');
        GuidebookRestApiController_MemberShip.createWebview(Comsite.Guide__c, Comsite.LTE__Site_URL__c, 'Testing Guide');
        Test.stopTest();
        
    }
}